version: '3.7'

services:

  fast:
    build: .
    image: alexanderfefelov/fastnetmon
    hostname: fast
    networks:
      - back
    volumes:
      -  /etc/localtime:/etc/localtime:ro
      - ./fastnetmon:/fastnetmon 
      - ./fastnetmon-attacks/:/fastnetmon-attacks/
    ports:
      - 2055:2055/udp
      - 6343:6343/udp
#    depends_on:
#      - mysql
#    env_file:
#      - ./.env_librenms
#   environment:
#     - TZ=America/Sao_Paulo
#     - POLLER=24
#     - SERVICES_ENABLED=1
#     - UPDATE_CHANNEL=master
#     - WEATHERMAP=1

networks:
    back:
       external:
             name: net
    default:


