version: '3.7'

services:

  fast:
    build: .
    image: dmarteleto/fastnetmon
    hostname: fast
    networks:
      - back
    volumes:
      -  /etc/localtime:/etc/localtime:ro
      - ./fastnetmon:/fastnetmon 
      - ./fastnetmon-attacks/:/fastnetmon-attacks/
    ports:
      - 2055:2055/udp
      - 6343:6343/udp

networks:
    back:
       external:
             name: net
    default:


